defaults:
  - base_model_config

name: LLaMA3.3-70b-Instruct
model_type: instruct
configs:
  model_name_or_path: unsloth/DeepSeek-R1-Distill-Llama-70B-bnb-4bit
  max_seq_len: 4096
  max_new_tokens: 12
