from .nq_swap import NQSwap
from .truthfulqa import TruthfulQA
from .memo_trap import MemoTrap
from .nq import NQ
from .triviaqa import TriviaQA
from .popqa import PopQA
from .ifeval import IFEval
from .halueval import HaluEval
from .xsum import XSum
from .musique import MuSiQue
